# Generated by Django 5.2.7 on 2025-11-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='live',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
