# Generated by Django 5.2.7 on 2025-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='active',
            field=models.TextField(default='valeur par defaut'),
        ),
    ]
