# Generated by Django 5.2.7 on 2025-11-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produit_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
